import { Dialog, Transition } from '@headlessui/react'
import { Fragment, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'

import { BiLogIn } from "react-icons/bi";
import { FiMenu } from "react-icons/fi";
import { IoClose } from "react-icons/io5";

export default function Home() {
  let [isOpen, setIsOpen] = useState(false)

  function closeModal() {
    setIsOpen(false)
  }

  function openModal() {
    setIsOpen(true)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='relative w-full h-screen bg-[url(/img/portada.jpg)] bg-no-repeat bg-cover'>
        <section className='absolute top-0 left-0 w-full h-full bg-black/60 text-white'>
          <div className='absolute top-0 left-0 w-full'>
            <nav className='w-4/5 flex justify-between items-center mt-10 mx-auto'>
              <span className='font-light text-white text-2xl uppercase'>Logo</span>

              <ul className='text-gray-300 md:hidden'>
                <li><Link className='' href={'/'}>Login</Link></li>
              </ul>

              <button className='hidden text-white text-xl md:block'><FiMenu/></button>
            </nav>
          </div>

          <div className='w-full h-full flex flex-col justify-center items-center text-center'>
            <h1 className='font-light text-6xl uppercase'>Sistema de notas <br /> academicas</h1>
            <button className='bg-theme-1 flex items-center gap-3 py-3 px-20 mt-16 rounded-full shadow-md text-sm duration-200 hover:bg-theme-2' onClick={openModal}><BiLogIn className='text-lg' /> Acceder al sistema</button>
          </div>
        </section>

        <Transition appear show={isOpen} as={Fragment}>
          <Dialog as="div" className="relative z-10" onClose={closeModal}>
            <Transition.Child as={Fragment} enter="ease-out duration-300" enterFrom="opacity-0" enterTo="opacity-100" leave="ease-in duration-200" leaveFrom="opacity-100" leaveTo="opacity-0">
              <div className="fixed inset-0 bg-black/25" />
            </Transition.Child>

            <div className="fixed inset-0 overflow-y-auto">
              <div className="flex min-h-full items-center justify-center p-4 text-center">
                <Transition.Child as={Fragment} enter="ease-out duration-300" enterFrom="opacity-0 scale-95" enterTo="opacity-100 scale-100" leave="ease-in duration-200" leaveFrom="opacity-100 scale-100" leaveTo="opacity-0 scale-95">
                  <Dialog.Panel className="relativo w-full max-w-md overflow-hidden bg-light-1 py-10 px-6 rounded-2xl transform text-left align-middle shadow-xl transition-all">
                    <button type="button" className='absolute top-0 right-0 p-0.5 m-3 text-gray-500 text-xl hover:text-gray-800' onClick={closeModal}>
                      <IoClose />
                    </button>

                    <div className='mt-5 text-center'>
                      <h3 className="text-gray-700 text-3xl leading-6">Acceder</h3>
                      <p className='mt-2.5 text-gray-500'>Inserta sus credenciales para continuar.</p>
                    </div>

                    <form onSubmit={''}>
                      <div className='flex flex-col gap-3 mt-10'>
                        <input className='w-full h-10 bg-white px-5 outline-none rounded-full shadow text-gray-700' type="number" name="" id="" placeholder='Cedula' />
                        <input className='w-full h-10 bg-white px-5 outline-none rounded-full shadow text-gray-700' type="password" name="" id="" placeholder='Contraseña' />
                      </div>

                      <div className='flex justify-between items-center my-7'>
                        <label className='flex items-center gap-2' htmlFor="memory">Recordar<input type="checkbox" name="" id="memory" /></label>
                        <Link className='text-sm underline hover:text-blue-500' href={'#'}>¿Olvidaste la contraseña?</Link>
                      </div>

                      <button className='block w-2/3 bg-blue-500 py-2 mx-auto rounded-full text-white hover:bg-blue-600'>Acceder</button>
                    </form>
                  </Dialog.Panel>
                </Transition.Child>
              </div>
            </div>
          </Dialog>
        </Transition>
      </header>
      <>


      </>
    </>
  )
}
